# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImovelRural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_incra', models.CharField(max_length=254, verbose_name='cód. do INCRA')),
                ('nome', models.CharField(max_length=254, verbose_name='nome')),
                ('certidao', models.CharField(max_length=254, verbose_name='certidão')),
                ('dt_certif', models.CharField(max_length=254, verbose_name='data da certificação')),
                ('proprietario', models.IntegerField(verbose_name='proprietário')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom')),
            ],
            options={
                'verbose_name': 'Imóvel Rural',
                'verbose_name_plural': 'Imóveis Rurais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('meso', models.CharField(max_length=100, verbose_name='mesoregião')),
                ('micro', models.CharField(max_length=100, verbose_name='microregião')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='sobrenome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geocodigo', models.CharField(max_length=20, verbose_name='geocódigo')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('ms_ucs', models.CharField(max_length=12, verbose_name='cultura')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom')),
            ],
            options={
                'verbose_name': 'Safra',
                'verbose_name_plural': 'Safras',
                'ordering': ['ms_ucs'],
            },
        ),
    ]
