# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImovelRural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_incra', models.CharField(max_length=254)),
                ('nome', models.CharField(max_length=254)),
                ('certidao', models.CharField(max_length=254)),
                ('dt_certif', models.CharField(max_length=254)),
                ('prop_id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Imóveis Rurais',
                'ordering': ['nome'],
                'verbose_name': 'Imóvel Rural',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('meso', models.CharField(max_length=100)),
                ('micro', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
                'verbose_name': 'Município',
            },
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geocodigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=60)),
                ('ms_ucs', models.CharField(max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Safras',
                'ordering': ['ms_ucs'],
                'verbose_name': 'Safra',
            },
        ),
    ]
