# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelrural',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proprietario', verbose_name='proprietário'),
        ),
    ]
