# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Proprietários',
                'verbose_name': 'Proprietário',
            },
        ),
    ]
