# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 22:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelrural',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom'),
        ),
    ]
