# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovelrural',
            name='prop_id',
        ),
        migrations.AddField(
            model_name='imovelrural',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Proprietario', verbose_name='proprietário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovelrural',
            name='certidao',
            field=models.CharField(max_length=254, verbose_name='certidão'),
        ),
        migrations.AlterField(
            model_name='imovelrural',
            name='cod_incra',
            field=models.CharField(max_length=254, verbose_name='cód. do INCRA'),
        ),
        migrations.AlterField(
            model_name='imovelrural',
            name='dt_certif',
            field=models.CharField(max_length=254, verbose_name='data da certificação'),
        ),
        migrations.AlterField(
            model_name='imovelrural',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom'),
        ),
        migrations.AlterField(
            model_name='imovelrural',
            name='nome',
            field=models.CharField(max_length=254, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='meso',
            field=models.CharField(max_length=100, verbose_name='mesoregião'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='micro',
            field=models.CharField(max_length=100, verbose_name='microregião'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='sobrenome',
            field=models.CharField(max_length=30, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='safra',
            name='geocodigo',
            field=models.CharField(max_length=20, verbose_name='geocódigo'),
        ),
        migrations.AlterField(
            model_name='safra',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom'),
        ),
        migrations.AlterField(
            model_name='safra',
            name='ms_ucs',
            field=models.CharField(max_length=12, verbose_name='cultura'),
        ),
        migrations.AlterField(
            model_name='safra',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='nome'),
        ),
    ]
