# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170325_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelrural',
            name='dt_certif',
            field=models.DateField(max_length=254, verbose_name='data da certificação'),
        ),
    ]
