# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170325_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPlantada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=255, verbose_name='Culturas')),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='área em hectares')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom')),
                ('imovel_rural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ImovelRural', verbose_name='imóvel rural')),
            ],
            options={
                'verbose_name_plural': 'áreas plantadas',
                'verbose_name': 'área plantada',
                'ordering': ['cultura'],
            },
        ),
    ]
