# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_areaplantada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaplantada',
            name='imovel_rural',
        ),
        migrations.DeleteModel(
            name='AreaPlantada',
        ),
    ]
