# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 19:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170416_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelrural',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326, verbose_name='geom'),
        ),
    ]
