# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 19:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170418_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelrural',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom'),
        ),
    ]
